# fly.toml app configuration file generated for band-db on 2025-03-28T13:22:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'band-db'
primary_region = 'iad'
kill_signal = 'SIGTERM'

[build]

[env]
  PHX_HOST = 'band-db.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
